theme: minima
title: Welcome to Corridors
author: Prakash
email:admin@corridors.in
description: > # this means to ignore newlines until "baseurl:"
  Want to switch your career in Datstructure and Algorithm Join Corridors Today.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
